### ISSUE TITLE
Generate an event with a signal to docker-gen

### ISSUE THREAD

**Issue by JrCs** [jwilder/docker-gen#162] opened 2016-02-15 09:02 UTC
Hi,

it will be great to be able to send a signal to docker-gen that create a "fake" event (like if a container is starting/dying).
With that we can "force" docker-gen to regenerate file(s) with template(s) without creating/stopping a container.

**Comment by jwilder** [comment] 2016-02-15 16:38
You can send a sighup signal to trigger a regeneration if the templates.

**Comment by spali** [comment] 2016-02-16 00:14
I searching for something similar.
But sighup isn't an option for me, because it kill the container. I also tried to exec into the container and send the sighup to the process itself, but with the same result.
The problem is, this could trigger other stuff when managed by docker-compose and/or similar scheduling components. I.e. in my case this would rebuild the whole stack of proxy.
I tried a workaround by invoking invoking ```docker-gen``` with the template inside the running docker-gen container. But against my assumption ```/usr/local/bin/docker-gen -only-exposed /my/template.tmpl /my/generated.file``` started ```docker-gen``` as "watching" process.
I would assume without ```-wait``` it would just generate the file and exit. But it waits as it would be started with ```-wait```.

Probably this is a bug?
@jwilder should I create a separate Issue for this or did I miss something?

**Comment by jwilder** [comment] 2016-02-16 00:21
@spali `sighup` won't kill `docker-gen` process.  Are you sure you are sending the signal to the correct process?  `docker-gen` not exiting should be fixed in `0.6` version.

**Comment by spali** [comment] 2016-02-16 00:28
I tried it with docker kill -signal=sighup to the docker-gen Container. As I know this should send it to the main process which is docker-gen.
Also tried docker exec to the container with pkill. Same result. 
Probalby I have to say I use alpine as base image for docker-gen. But beside this the Image is exaclty the same setup as your original one.

Am 16. Februar 2016 01:21:41 MEZ, schrieb Jason Wilder <notifications@github.com>:

**Comment by JrCs** [comment] 2016-02-16 08:31
It seems to work with version 0.6.0.
Thanks @jwilder

**Comment by spali** [comment] 2016-02-16 18:57
I can confirm it to, sighup works with 0.6.0
thanks

**Closed** 2016-02-16 20:11 UTC
